server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kosta.bus_reserve.domain

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE


    username: practice2
    password: 2222

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp